package cabreservationsystem;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Cab extends javax.swing.JFrame {

    /**
     * Creates new form Cab
     */
    public Cab() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Connect();
        LoadCabID();
        Fetch();
        setTitle("Cab");
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public final void Connect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/crsdb", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Cab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean InputValidation(){
        if(txtBrand.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Missing input Brand", "SAVE ERROR", JOptionPane.WARNING_MESSAGE);
            return false; 
        }else if(txtModel.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Missing input Model", "SAVE ERROR", JOptionPane.WARNING_MESSAGE);
            return false; 
        }else{
            return true;
        }
    }
    
    public final void LoadCabID() {
    	
    	try {
			pst = con.prepareStatement("SELECT cabID FROM cab");
			rs = pst.executeQuery();
			comboCabID.removeAllItems();
			while(rs .next()) {
				comboCabID.addItem(rs.getString(1));	
			}
					
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Cab.class.getName()).log(Level.SEVERE, null, ex);
		}
    }
    
    private void Fetch() {
    	int a;
    	try {
			pst = con.prepareStatement("SELECT * FROM cab");
			rs = pst.executeQuery();
			ResultSetMetaData rss = rs.getMetaData();
			a = rss.getColumnCount();
			
			
			DefaultTableModel df = (DefaultTableModel)tblCab.getModel();
			df.setRowCount(0);
			while(rs.next()){
				Vector v2 = new Vector();
				for(int b=1; b<=a; b++) {
					v2.add(rs.getString("cabID"));
					v2.add(rs.getString("cabBrand"));
					v2.add(rs.getString("cabModel"));
				}	
				df.addRow(v2);
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Cab.class.getName()).log(Level.SEVERE, null, ex);
		}	
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        btnPassenger = new javax.swing.JButton();
        lblCab = new javax.swing.JLabel();
        btnDriver = new javax.swing.JButton();
        btnReservation = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        lblCID = new javax.swing.JLabel();
        comboCabID = new javax.swing.JComboBox<>();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCab = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navPanel.setBackground(new java.awt.Color(0, 153, 153));

        btnPassenger.setBackground(new java.awt.Color(0, 153, 153));
        btnPassenger.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPassenger.setText("Passenger");
        btnPassenger.setBorderPainted(false);
        btnPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassengerActionPerformed(evt);
            }
        });

        lblCab.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCab.setForeground(new java.awt.Color(255, 255, 255));
        lblCab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCab.setText("Cab");
        lblCab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnDriver.setBackground(new java.awt.Color(0, 153, 153));
        btnDriver.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDriver.setText("Driver");
        btnDriver.setBorderPainted(false);
        btnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverActionPerformed(evt);
            }
        });

        btnReservation.setBackground(new java.awt.Color(0, 153, 153));
        btnReservation.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnReservation.setText("Reservation");
        btnReservation.setBorderPainted(false);
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });

        btnSchedule.setBackground(new java.awt.Color(0, 153, 153));
        btnSchedule.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSchedule.setText("Schedule");
        btnSchedule.setBorderPainted(false);
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 153, 153));
        btnExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 51));
        btnExit.setText("Exit");
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPassenger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCab, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addComponent(btnDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPassenger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(navPanelLayout.createSequentialGroup()
                                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCab, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblCID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCID.setText("Cab ID:");
        lblCID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        comboCabID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCabID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCabIDActionPerformed(evt);
            }
        });

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        lblBrand.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblBrand.setText("Brand:");
        lblBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblModel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblModel.setText("Model:");
        lblModel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblCab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cab ID", "Brand", "Model"
            }
        ));
        jScrollPane1.setViewportView(tblCab);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtBrand))
                        .addGap(116, 116, 116)
                        .addComponent(lblCID)
                        .addGap(18, 18, 18)
                        .addComponent(comboCabID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit1)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCID)
                    .addComponent(comboCabID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addGap(35, 35, 35)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit1)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverActionPerformed
        Driver d = new Driver();
        d.show();
        
        dispose();
    }//GEN-LAST:event_btnDriverActionPerformed

    private void btnPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassengerActionPerformed
        Passenger p = new Passenger();
        p.show();
        
        dispose();
    }//GEN-LAST:event_btnPassengerActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        Reservation r = new Reservation();
        r.show();
        
        dispose();
    }//GEN-LAST:event_btnReservationActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        Schedule s = new Schedule();
        s.show();
        
        dispose();
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void comboCabIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCabIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCabIDActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        
        if(InputValidation()!=false){
    	String cabBrand = txtBrand.getText();
    	String cabModel = txtModel.getText();
    	String cabID = comboCabID.getSelectedItem().toString();
    	
    	try {
			pst = con.prepareStatement("UPDATE cab SET cabBrand=?,cabModel=? WHERE cabID=?");
			pst.setString(1, cabBrand);
			pst.setString(2, cabModel);
			pst.setString(3, cabID);
			
			int k = pst.executeUpdate();
			
			if(k==1) {
				 JOptionPane.showMessageDialog(this, "Data is update successfully.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
				 txtBrand.setText("");
				 txtModel.setText("");
				 comboCabID.requestFocus();
				 Fetch();
				 	LoadCabID();
			}else {
				JOptionPane.showMessageDialog(this, "Data is not update successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Cab.class.getName()).log(Level.SEVERE, null, ex);
		}	
      }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        if(InputValidation()!=false){
    	String cabBrand = txtBrand.getText();
    	String cabModel = txtModel.getText();
   
  	 try {
			pst = con.prepareStatement("INSERT INTO cab (cabBrand,cabModel)VALUES(?,?)");
                        pst.setString(1,cabBrand);
			pst.setString(2,cabModel);
			
			
			int k = pst.executeUpdate();
			
			if(k==1) {
				 JOptionPane.showMessageDialog(this, "Data is added successfully.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
				 txtBrand.setText("");
				 txtModel.setText("");
				 Fetch();
				 	LoadCabID();
			}else {
				JOptionPane.showMessageDialog(this, "Data is not added successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			Logger.getLogger(Cab.class.getName()).log(Level.SEVERE, null, ex);
		}
     }		
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String cabID = comboCabID.getSelectedItem().toString();
    	try {
			pst=con.prepareStatement("DELETE FROM cab WHERE cabID=?");
			pst.setString(1, cabID);
			
			int k = pst.executeUpdate();
			if(k==1) {
				JOptionPane.showMessageDialog(this, "Data is deleted successfully.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
				 txtBrand.setText("");
				 txtModel.setText("");
				 comboCabID.requestFocus();
				 Fetch();
				 	LoadCabID();
			}else {
				JOptionPane.showMessageDialog(this, "Data is not deleted successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			Logger.getLogger(Cab.class.getName()).log(Level.SEVERE, null, ex);
		}	
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String cabID = comboCabID.getSelectedItem().toString();
    	
    	try {
			pst = con.prepareStatement("SELECT * FROM cab WHERE cabID=?");
			pst.setString(1, cabID);
			rs = pst.executeQuery();
			
			if(rs.next()==true){
				 txtBrand.setText(rs.getString(2));
				 txtModel.setText(rs.getString(3));
			}else {
				JOptionPane.showMessageDialog(this, "No Record Found!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Cab.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.show();
        
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPassenger;
    private javax.swing.JButton btnReservation;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboCabID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCID;
    private javax.swing.JLabel lblCab;
    private javax.swing.JLabel lblModel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JTable tblCab;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables
}
