/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabreservationsystem;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Driver extends javax.swing.JFrame {

    /**
     * Creates new form Driver
     */
    public Driver() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Connect();
        LoadDriverID();
        Fetch();
        setTitle("Driver");
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/crsdb", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean InputValidation(){
        if(txtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Missing input First Name", "SAVE ERROR", JOptionPane.WARNING_MESSAGE);
            return false; 
        }else if(txtLastName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Missing input Last Name", "SAVE ERROR", JOptionPane.WARNING_MESSAGE);
            return false; 
        }else if(txtContact.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Missing input Contact Number", "SAVE ERROR", JOptionPane.WARNING_MESSAGE);
            return false; 
        }else if (txtSalary.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Missing input Salary", "SAVE ERROR", JOptionPane.WARNING_MESSAGE);
            return false;  
        }else{
            return true;
        }
    }
    
    public void LoadDriverID() {
    	
    	try {
			pst = con.prepareStatement("SELECT driverID FROM driver");
			rs = pst.executeQuery();
			comboDriverID.removeAllItems();
			while(rs .next()) {
				comboDriverID.addItem(rs.getString(1));	
			}
					
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
		}
    }
    
    private void Fetch() {
    	int a;
    	try {
			pst = con.prepareStatement("SELECT * FROM driver");
			rs = pst.executeQuery();
			ResultSetMetaData rss = rs.getMetaData();
			a = rss.getColumnCount();
			
			
			DefaultTableModel df = (DefaultTableModel)tblDriver.getModel();
			df.setRowCount(0);
			while(rs.next()){
				Vector v2 = new Vector();
				for(int b=1; b<=a; b++) {
					v2.add(rs.getString("driverID"));
					v2.add(rs.getString("firstName"));
					v2.add(rs.getString("lastName"));
					v2.add(rs.getString("contactNo"));
					v2.add(rs.getString("salary"));
				}	
				df.addRow(v2);
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
		}	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        btnCab = new javax.swing.JButton();
        btnReservation = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        btnPassenger = new javax.swing.JButton();
        lblDriver = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        lblDID = new javax.swing.JLabel();
        comboDriverID = new javax.swing.JComboBox<>();
        lblDFN = new javax.swing.JLabel();
        lblDLN = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblDCN = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDriver = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navPanel.setBackground(new java.awt.Color(0, 153, 153));

        btnCab.setBackground(new java.awt.Color(0, 153, 153));
        btnCab.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCab.setText("Cab");
        btnCab.setBorderPainted(false);
        btnCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabActionPerformed(evt);
            }
        });

        btnReservation.setBackground(new java.awt.Color(0, 153, 153));
        btnReservation.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnReservation.setText("Reservation");
        btnReservation.setBorderPainted(false);
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });

        btnSchedule.setBackground(new java.awt.Color(0, 153, 153));
        btnSchedule.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSchedule.setText("Schedule");
        btnSchedule.setBorderPainted(false);
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        btnPassenger.setBackground(new java.awt.Color(0, 153, 153));
        btnPassenger.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPassenger.setText("Passenger");
        btnPassenger.setBorderPainted(false);
        btnPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassengerActionPerformed(evt);
            }
        });

        lblDriver.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDriver.setForeground(new java.awt.Color(255, 255, 255));
        lblDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriver.setText("Driver");
        lblDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnExit.setBackground(new java.awt.Color(0, 153, 153));
        btnExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 51));
        btnExit.setText("Exit");
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPassenger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCab, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addComponent(lblDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPassenger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(navPanelLayout.createSequentialGroup()
                                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCab, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblDID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDID.setText("Driver ID:");
        lblDID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        comboDriverID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDriverID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDriverIDActionPerformed(evt);
            }
        });

        lblDFN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDFN.setText("First Name:");
        lblDFN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblDLN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDLN.setText("Last Name:");
        lblDLN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblDCN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDCN.setText("Contact No.");
        lblDCN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSalary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSalary.setText("Salary:");
        lblSalary.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        tblDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Driver ID", "First Name", "Last Name", "Contact No.", "Salary"
            }
        ));
        jScrollPane1.setViewportView(tblDriver);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDLN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDFN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(comboDriverID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblDCN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDID)
                    .addComponent(comboDriverID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDFN)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDCN)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDLN)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalary)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabActionPerformed
        Cab c = new Cab();
        c.show();
        
        dispose();
    }//GEN-LAST:event_btnCabActionPerformed

    private void comboDriverIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDriverIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDriverIDActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void btnPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassengerActionPerformed
        Passenger p = new Passenger();
        p.show();
        
        dispose();
    }//GEN-LAST:event_btnPassengerActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        Reservation r = new Reservation();
        r.show();
        
        dispose();
    }//GEN-LAST:event_btnReservationActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        Schedule s = new Schedule();
        s.show();
        
        dispose();
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        if(InputValidation()!=false){
    	String firstName = txtFirstName.getText();
    	String lastName = txtLastName.getText();
    	String contact = txtContact.getText();
    	String salary = txtSalary.getText();
    	String driverID = comboDriverID.getSelectedItem().toString();
    	
    	try {
			pst = con.prepareStatement("UPDATE driver SET firstName=?,lastName=?,contactNo=?,salary=? WHERE driverID=?");
			pst.setString(1, firstName);
			pst.setString(2, lastName);
			pst.setString(3, contact);
			pst.setString(4, salary);
			pst.setString(5, driverID);
			
			int k = pst.executeUpdate();
			
			if(k==1) {
				 JOptionPane.showMessageDialog(this, "Data is update successfully.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
				 txtFirstName.setText("");
				 txtLastName.setText("");
				 txtContact.setText("");
				 txtSalary.setText("");
				 comboDriverID.requestFocus();
				 Fetch();
				 	LoadDriverID();
			}else {
				JOptionPane.showMessageDialog(this, "Data is not update successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
		}	
     }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(InputValidation()!=false){
    	String firstName = txtFirstName.getText();
    	String lastName = txtLastName.getText();
        String contact = txtContact.getText();
        String salary = txtSalary.getText();
    	
    	try {
  			pst = con.prepareStatement("INSERT INTO driver (firstName,lastName,contactNo,salary)VALUES(?,?,?,?)");
  			pst.setString(1,firstName);
  			pst.setString(2,lastName);
  			pst.setString(3,contact);
  			pst.setString(4,salary);
  			
  			int k = pst.executeUpdate();
  			
  			if(k==1) {
  				 JOptionPane.showMessageDialog(this, "Data is added successfully.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
  				 txtFirstName.setText("");
  				 txtLastName.setText("");
  				 txtContact.setText("");
  				 txtSalary.setText("");
  				 Fetch();
                                 LoadDriverID();
  			}else {
  				JOptionPane.showMessageDialog(this, "Data is not added successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
  			}
  			
  		} catch (SQLException ex) {
  			// TODO Auto-generated catch block
  			Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
  		}
     }	
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String driverID = comboDriverID.getSelectedItem().toString();
    	try {
			pst=con.prepareStatement("DELETE FROM driver WHERE DriverID=?");
			pst.setString(1, driverID);
			
			int k = pst.executeUpdate();
			if(k==1) {
				JOptionPane.showMessageDialog(this, "Data is deleted successfully.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
				 txtFirstName.setText("");
				 txtLastName.setText("");
				 txtContact.setText("");
				 txtSalary.setText("");
				 comboDriverID.requestFocus();
				 Fetch();
				 	LoadDriverID();
			}else {
				JOptionPane.showMessageDialog(this, "Data is not deleted successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String driverID = comboDriverID.getSelectedItem().toString();
    	
    	try {
			pst = con.prepareStatement("SELECT * FROM driver WHERE DriverID=?");
			pst.setString(1, driverID);
			rs = pst.executeQuery();
			
			if(rs.next()==true){
				 txtFirstName.setText(rs.getString(2));
				 txtLastName.setText(rs.getString(3));
				 txtContact.setText(rs.getString(4));
				 txtSalary.setText(rs.getString(5));
			}else {
				JOptionPane.showMessageDialog(this, "No Record Found!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.show();

        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCab;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPassenger;
    private javax.swing.JButton btnReservation;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboDriverID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDCN;
    private javax.swing.JLabel lblDFN;
    private javax.swing.JLabel lblDID;
    private javax.swing.JLabel lblDLN;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JTable tblDriver;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
